FROM ubuntu:20.04

LABEL Description="MEICAN Image" \
      Author="Leonardo Lauryel Batista dos Santos"

ARG MEICAN_VERSION \ 
   DEBIAN_FRONTEND=noninteractive \
   DEBCONF_NONINTERACTIVE_SEEN=true

ENV MYSQL_DATABASE=$MYSQL_DATABASE \
   MYSQL_USER=$MYSQL_USER \
   MYSQL_PASSWORD=$MYSQL_PASSWORD \
   MEICAN_DIR=/home/meican/meican-$MEICAN_VERSION
   
RUN apt-get update \
 && apt-get install -yq --no-install-recommends \
    apt-utils \
    curl \
    sudo \
    zip \
    unzip \
    # Install apache
    apache2 \
    # Install php 7.4
    php7.4 \
    php7.4-mysql \
    php7.4-mbstring \
    php7.4-curl \
    php7.4-soap \
    php7.4-xml \
    libapache2-mod-php \
 && rm -rf /var/lib/apt/lists/*

RUN adduser --disabled-password --gecos '' meican \
 && usermod -aG sudo meican \
 && cd / \
 && curl -kO https://getcomposer.org/download/1.10.27/composer.phar

WORKDIR $MEICAN_DIR

RUN curl -kO https://getcomposer.org/download/1.10.27/composer.phar \
 && su meican -c "php composer.phar global require "fxp/composer-asset-plugin:~1.4.4"" \
 && ln -s $MEICAN_DIR/web /var/www/meican \
 && a2enmod rewrite

COPY 000-default.conf /etc/apache2/sites-available/

COPY docker-entrypoint.sh /

EXPOSE 80

ENTRYPOINT ["/docker-entrypoint.sh"]
